In [5]:
import numpy as np
import time

In [12]:
# execution performance
size = 1_000_000
# python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 0.4457240104675293 seconds
numpy array time = 0.01189422607421875 seconds


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr,type(arr.shape))
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2,type(arr2.dtype))

# create
arr1 = np.zeros([2,3])
print(arr1, arr1.shape)

arr2 = np.ones([5,])
print(arr2, arr2.shape)


array = np.ones(10) * 7
print(array)
arr3 = np.full((3, 4), 100)
print(arr3, arr3.shape)


[1 2 3 4 5] <class 'tuple'>
[1 2 3 4 5] <class 'numpy.dtypes.Int64DType'>
[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [27]:
# reshaping
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)
# flattened converting in one dimensionl array
flattened = arr.flatten()
print(flattened,flattened.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [32]:
# indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[3])

# fancy indexing
idx = [0, 1, 3]
print(arr[idx])

# boolean indexing
print([arr >2])
print(arr[2:])

# slicing
print(arr[1 : 4])

1
4
[1 2 4]
[array([False, False,  True,  True,  True])]
[3 4 5]
[2 3 4]


In [36]:
# multi dimensional array 
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [48]:
import numpy as np 
arr1 = np.array([1, 2, 3,4])
arr2 = np.array([5, 6, 7, 8])
print(np.add(arr1, arr2))


[ 6  8 10 12]


In [10]:
import numpy as np

# Creating a NumPy array 'a' containing integers from 10 to 21 and reshaping it into a 3x4 matrix using np.arange() and .reshape()
a = np.arange(10, 22).reshape((3, 4))

# Printing a message indicating the original array 'a'
print("Original array:")
print(a)

# Printing a message indicating each element of the array using np.nditer() to iterate through the elements
print("Each element of the array is:")
for x in np.nditer(a):
    print(x , end=" ") 


Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [14]:
#MULTIPLICATON OF TWO VECTORS

import numpy as np 
x = np.array([1, 8, 3, 5])
print("vector-1")
print(x)
y = np.random.randint(0, 11, 4)
print("vector-2")
print(y)
result = x * y
print(result)

vector-1
[1 8 3 5]
vector-2
[3 8 7 2]
[ 3 64 21 10]


In [27]:
import numpy as np
x = np.arange(12, 39)
print("original array")
print(x)
x = x[:: -1]
print(x)

original array
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [17]:
import numpy as np
x = np.ones ((10, 10))
x[1:-1 , 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
import numpy as np
x = np.diag((1, 2, 3, 4, 5))
print(x)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [47]:
import numpy as np
x = np.array([4,5, 2])
y = np.array([4,3,5])
print(x)
print(y)
print(np.dot(x, y))
print(np.cross(x, y))

[4 5 2]
[4 3 5]
41
[ 19 -12  -8]


## import numpy as np
x = np.random.random((5,3 ))
print( "array-1")
print(x)
y = np.random.random((3, 2 ))
print("array-2")
print(y)
print("now the dot product")
print(np.dot(x , y))


In [39]:
import numpy as np
x =np.array([1+2j, 3+4j])
print(x)
y = np.array([5+2j, 2+1j])
print(y)
print(np.vdot(x,y))

[1.+2.j 3.+4.j]
[5.+2.j 2.+1.j]
(19-13j)


In [51]:
from numpy.polynomial import polynomial as P
x = np.array([1, 2, 3,4])
y = np.array([5, 6, 7, 8])
print(P.polyadd(x, y))
print(P.polysub(x, y))
print(P.polymul(x, y))
print(P.polydiv(x, y))

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 16. 34. 60. 61. 52. 32.]
(array([0.5]), array([-1.5, -1. , -0.5]))


In [55]:
x =np.array([[10, 30], [20, 60]])

# Displaying the original array
print(x)
#Displaying the mean of each column
print(" mean of each column")
print(x.mean(axis=0))
print(" mean of each row")
print(x.mean(axis=1))

[[10 30]
 [20 60]]
 mean of each column
[15. 45.]
 mean of each row
[20. 40.]


In [67]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print("Original Array")
print(x)
print(np.cumsum(x))
print("Comulative sum of  Row ")
print(np.cumsum(x, axis=0)) 
print("Cumulative sum of each Column")
print(np.cumsum(x, axis=1)) 

Original Array
[[1 2 3]
 [4 5 6]]
[ 1  3  6 10 15 21]
Comulative sum of  Row 
[[1 2 3]
 [5 7 9]]
Cumulative sum of each Column
[[ 1  3  6]
 [ 4  9 15]]


In [68]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print("Original Array")
print(x)
print(np.cumprod(x))
print("Comulative sum of  Row ")
print(np.cumprod(x, axis=0)) 
print("Cumulative sum of each Column")
print(np.cumprod(x, axis=1)) 

Original Array
[[1 2 3]
 [4 5 6]]
[  1   2   6  24 120 720]
Comulative sum of  Row 
[[ 1  2  3]
 [ 4 10 18]]
Cumulative sum of each Column
[[  1   2   6]
 [  4  20 120]]


In [78]:
# Creating an array
x = np.array([1, 2, 3, 4, 5], np.float32)
print(np.diff(x))
print(np.exp(x))
print(np.exp(x) - 1) # exponential -1
# Calculating natural logarithm (base e) of the array elements
print("\nNatural log =", np.log(x))

# Calculating common logarithm (base 10) of the array elements
print("Common log =", np.log10(x))

# Calculating base 2 logarithm of the array elements
print("Base 2 log =", np.log2(x)) 

r1 = np.reciprocal(x)

# Calculating the reciprocal of each element in array x using the reciprocal operator (1/x)
r2 = 1/x

# Checking if the results from np.reciprocal() and the reciprocal operator are equal using np.array_equal()
assert np.array_equal(r1, r2)

# Displaying the reciprocals for all elements of the array obtained using np.reciprocal()
print("Reciprocal for all elements of the said array:")
print(r1) 
print(np.power(x,r1))

[1. 1. 1. 1.]
[  2.7182817   7.389056   20.085537   54.59815   148.41316  ]
[  1.7182817   6.389056   19.085537   53.59815   147.41316  ]

Natural log = [0.        0.6931472 1.0986123 1.3862944 1.609438 ]
Common log = [0.         0.30103    0.47712126 0.60206    0.69897   ]
Base 2 log = [0.        1.        1.5849625 2.        2.321928 ]
Reciprocal for all elements of the said array:
[1.         0.5        0.33333334 0.25       0.2       ]
[1.        1.4142135 1.4422495 1.4142135 1.3797296]
